validation: sovereign
version: 1
accounts:
  - name: aa1
    coins:
      - 20000token
      - 200000000stake
faucet:
  name: bob
  coins:
    - 5token
    - 100000stake
client:
  typescript:
    path: ts-client
  hooks:
    path: react/src/hooks
  openapi:
    path: docs/static/openapi.yml
validators:
  - name: aa1
    bonded: 100000000stake
